# This file is used with the -backend-config flag
# e.g., terraform init -backend-config=backend.conf

storage_account_name = "tfstate79smpa"
container_name       = "tfstate"
key                  = "document-portal-next-azure-dev.tfstate"
resource_group_name  = "rg-terraform-state"
